### ISSUE TITLE
三水平元分析中相关系数与样本量的转换问题

### ISSUE THREAD

**Issue by yunqingchushang** [ShixiangWang/ShixiangWang.github.io#1]
在用R进行三水平元分析的时候，需要将搜集到的相关系数和样本量用R中的rma.mv函数将相关系数和样本量转化成Fisher'z值和方差,说是可以通过标准误差的平方得到。这后面是原文的描述(The variable labeled y contains all actual effectsizes,and in this example,all effects are expressed in Cohen’s d (but other metrics for the effectsize,such as Fisher’s z,can also be analyzed with the rma.mv function of the metafor package).Each effectsize represents the difference in recidivism rates between juveniles with a mental health disorder and a comparison group of juveniles without a mental health disorder .A positive value of Cohen’s d indicates that the prevalence of recidivism is higher in the group of juveniles with a mental health disorder relative to the comparis on group,whereas a negative value of Cohen’s d is indicative of the opposite. According to the criteria formulated byCohen(1988),d values of.2,.5,and.8 can be interpreted as small,moderate, and large effects,respectively. The variable labeled v contains the sampling variance that corresponds with the observed effectsize in the variable y and can be obtained by squaring the standard error. )。但是原文没有说怎么操作，我找了很多资料也没有看到。所以想请教一下大神。(附件是原文给出的数据。所以，我就想知道将相关系数和样本量转换成下面的y(fisher' z)和v(方差)的。谢谢大神了！)
![无标题](https://user-images.githubusercontent.com/52899954/61193691-a8267d00-a6ef-11e9-90a1-edda35697400.png)

**Comment by ShixiangWang** [comment]
Sorry,才看到，这不是一个提问的地方，不好意思。
